version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn test
      - run: yarn size
      - persist_to_workspace:
          root: ~/project
          paths: .
  publish:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Setup npm auth
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish to npm
          command: node scripts/publish.js

workflows:
  version: 2
  build-and-publish:
    jobs:
      # run the build job on all branches and tags
      - build:
          filters: # required since `publish` has tag filters and requires `build`
            tags:
              only: /.*/
      # run the publish job only on v* tags
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
